version: "3.8"
services:

  mysqldb:
    container_name: mysqldb
    image: mysql
    env_file: ./.env
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD

  eureka-server:
    container_name: EUREKA-SERVER
    image: efigueredo/service-registry:1.0
    restart: always
    build: .
    ports:
      - 8761:8761

  gateway:
    container_name: GATEWAY
    image: efigueredo/gateway:1.0
    restart: always
    env_file: ./.env
    build: .
    ports:
      - 8080:8080
    environment:
      EUREKA_PORT: 8761
      EUREKA_HOST: eureka-server
      IDENTIDADE_HOST: $IDENTIDADE_HOST
    depends_on:
      - eureka-server
      - mysqldb

  ms-identidade:
    container_name: MS_IDENTIDADE
    image: efigueredo/ms-identidade:1.0
    depends_on:
      - gateway
      - eureka-server
      - mysqldb
    restart: always
    env_file: ./.env
    build: .
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_PORT: $MYSQL_PORT
      EUREKA_PORT: $EUREKA_PORT
      EUREKA_HOST: eureka-server
      SECRET_KEY: $SECRET_KEY

  ms-anotacoes:
    container_name: MS-ANOTACOES
    depends_on:
      - eureka-server
      - ms-identidade
      - gateway
      - mysqldb
    image: efigueredo/ms-anotacoes:1.2
    restart: always
    build: .
    env_file: ./.env
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_PORT: $MYSQL_PORT
      EUREKA_PORT: $EUREKA_PORT
      EUREKA_HOST: eureka-server

