server:
  port: 20001

spring:
  application:
    name: SERVICE-ANOTACOES

  datasource:
    url: jdbc:mysql://localhost:3306/ms_anotacoes?createDatabaseIfNotExist=true
    username: root
    password: wall2003
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
