spring:
  application:
    name: ms-anotacoes

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/ms_anotacoes?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: 8081
