spring:
  cloud:
    gateway:
      routes:
        - id: ms-anotacoes
          uri: lb://ms-anotacoes
          predicates:
            - Path=/anotacoes/**
          filters:
            - AutenticacaoFilter

        - id: ms-identidade
          uri: lb://ms-identidade
          predicates:
            - Path=/identidade/**

  application:
    name: SERVICE-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/