spring:
  application:
    name: SERVICE-GATEWAY

  cloud:
    gateway:
      routes:
        - id: SERVICE-ANOTACOES
          uri: lb://SERVICE-ANOTACOES
          predicates:
            - Path=/anotacoes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/