spring:
  cloud:
    gateway:
      routes:
        - id: ms-anotacoes
          uri: lb://ms-anotacoes
          predicates:
            - Path=/anotacoes/**

        - id: ms-identidade
          uri: lb://ms-identidade
          predicates:
            - Path=/identidade/**

  application:
    name: SERVICE-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/